[pytest]
pythonpath = src
testpaths = test
python_files = test_*.py
python_classes = *Test
python_functions = test_*
addopts = 
    -v
    --cov=src
    --cov-report=term-missing
    --color=yes
    -ra
    --cov-fail-under=80